// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cpbqtbmmtnqibstyghwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwYnF0Ym1tdG5xaWJzdHlnaHdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNTgxMjMsImV4cCI6MjA2NDczNDEyM30._dLsoswMb5dl61tFK8Gk0lJ7G6Ia0gVfihkoKfwaf8w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);